# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userprofile', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Firstname', max_length=30)),
                ('middle', models.CharField(help_text='middle', max_length=2)),
                ('last_name', models.CharField(help_text='lastname', max_length=30)),
                ('birthdate', models.CharField(help_text='yyyy-mm-dd', max_length=10)),
                ('mobile_no', models.CharField(help_text='lastname', max_length=20)),
                ('address', models.CharField(blank=True, help_text='address', max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=50, null=True)),
                ('state', models.CharField(blank=True, help_text='State', max_length=50, null=True)),
                ('country', models.CharField(choices=[('ph', 'Philippines'), ('sg', 'Singapore')], db_index=True, default='ph', max_length=3)),
                ('zip_code', models.CharField(blank=True, help_text='Zip Code', max_length=10, null=True)),
                ('identification_type', models.CharField(choices=[('1', 'SSS'), ('0', 'none'), ('3', "Driver's License"), ('2', 'Passport')], db_index=True, default='0', max_length=3)),
                ('identification_no', models.CharField(blank=True, help_text="e.g SSS / Driver's License / Passport", max_length=50, null=True)),
                ('img_url', models.CharField(blank=True, help_text='image filename', max_length=20, null=True)),
                ('fb_url', models.CharField(blank=True, help_text='facebook profile', max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date the record was created')),
                ('last_modified_by', models.DateTimeField(auto_now=True, help_text='Date the record was last edited.', null=True)),
                ('last_modified', models.ForeignKey(blank=True, help_text='User who last updated the profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_last_updated', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(help_text='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
