# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='middle',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, help_text='middle name', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='identification_type',
            field=models.CharField(choices=[('1', 'SSS'), ('2', 'Passport'), ('0', 'none'), ('3', "Driver's License")], db_index=True, default='0', max_length=3),
        ),
    ]
